# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sum.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sum.proto", :syntax => :proto3) do
    add_message "sum.Session" do
      optional :access_token, :string, 1
      optional :updated_at, :message, 2, "google.protobuf.Timestamp"
      optional :user_agent, :string, 3
      optional :ip_address, :string, 4
    end
    add_message "sum.CreateSessionRequest" do
      optional :session, :message, 1, "sum.Session"
      optional :username, :string, 2
      optional :password, :string, 3
    end
    add_message "sum.DeleteSessionRequest" do
      optional :session_id, :string, 1
    end
    add_message "sum.ListSessionsRequest" do
      optional :page_token, :string, 1
      optional :page_size, :int32, 2
      optional :order_by, :string, 3
    end
    add_message "sum.ListSessionsResponse" do
      repeated :sessions, :message, 1, "sum.Session"
      optional :next_page_token, :string, 2
    end
    add_message "sum.CreateUserRequest" do
      optional :user, :message, 1, "sum.User"
    end
    add_message "sum.DeleteUserRequest" do
      optional :user_id, :string, 1
    end
    add_message "sum.GetUserRequest" do
      optional :user_id, :string, 1
    end
    add_message "sum.ListUsersRequest" do
      optional :page_token, :string, 1
      optional :page_size, :int32, 2
      optional :order_by, :string, 3
    end
    add_message "sum.UpdateUserRequest" do
      optional :user, :message, 1, "sum.User"
    end
    add_message "sum.ListUsersResponse" do
      repeated :users, :message, 1, "sum.User"
      optional :next_page_token, :string, 2
    end
    add_message "sum.User" do
      optional :id, :string, 1
      optional :admin, :bool, 2
      optional :updated_at, :message, 3, "google.protobuf.Timestamp"
      optional :username, :string, 4
      optional :password, :string, 5
      optional :name, :string, 6
      optional :email, :string, 7
      optional :email_verified, :bool, 8
      optional :phone_number, :string, 9
      optional :phone_number_verified, :bool, 10
      optional :picture, :string, 11
      optional :birthdate, :string, 12
      optional :locale, :string, 13
      optional :zoneinfo, :string, 14
    end
  end
end

module Sum
  Session = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.Session").msgclass
  CreateSessionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.CreateSessionRequest").msgclass
  DeleteSessionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.DeleteSessionRequest").msgclass
  ListSessionsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.ListSessionsRequest").msgclass
  ListSessionsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.ListSessionsResponse").msgclass
  CreateUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.CreateUserRequest").msgclass
  DeleteUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.DeleteUserRequest").msgclass
  GetUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.GetUserRequest").msgclass
  ListUsersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.ListUsersRequest").msgclass
  UpdateUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.UpdateUserRequest").msgclass
  ListUsersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.ListUsersResponse").msgclass
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.User").msgclass
end
