# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: sum.proto for package 'sum'

require 'grpc'
require 'sum_pb'

module Sum
  module Sessions
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'sum.Sessions'

      rpc :GetAuthenticationMethods, ::Sum::GetAuthenticationMethodsRequest, ::Sum::GetAuthenticationMethodsResponse
      rpc :Create, ::Sum::CreateSessionRequest, ::Sum::Session
      rpc :Delete, ::Sum::DeleteSessionRequest, ::Google::Protobuf::Empty
      rpc :Get, ::Sum::GetSessionRequest, ::Sum::Session
      rpc :List, ::Sum::ListSessionsRequest, ::Sum::ListSessionsResponse
      rpc :Update, ::Sum::UpdateSessionRequest, ::Sum::Session
    end

    Stub = Service.rpc_stub_class
  end
  module Users
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'sum.Users'

      rpc :Create, ::Sum::CreateUserRequest, ::Sum::User
      rpc :Delete, ::Sum::DeleteUserRequest, ::Google::Protobuf::Empty
      rpc :Get, ::Sum::GetUserRequest, ::Sum::User
      rpc :List, ::Sum::ListUsersRequest, ::Sum::ListUsersResponse
      rpc :Update, ::Sum::UpdateUserRequest, ::Sum::User
    end

    Stub = Service.rpc_stub_class
  end
end
