source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.1"

gem "rails"
gem "puma"

gem "sprockets-rails"
gem "jsbundling-rails"
gem "cssbundling-rails"
gem "sassc-rails"

gem "turbo-rails"
gem "stimulus-rails"

gem "grpc"
gem "view_component"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development, :test do
  gem "grpc-tools"
  gem "debug", platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem "hotwire-livereload"
  gem "web-console"
end
