AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*

Bundler/OrderedGems:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false
