source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.1"

gem "bootsnap", require: false
gem "rails"
gem "puma"
gem "sqlite3"
gem "redis"

gem "sprockets-rails"
gem "jsbundling-rails"
gem "cssbundling-rails"
gem "dartsass-rails"
gem "jbuilder"
gem "sassc-rails"
gem "image_processing"

gem "turbo-rails"
gem "stimulus-rails"

gem "bcrypt"
gem "jwt"
gem "rbnacl"
gem "rqrcode"
gem "trailblazer-rails"
gem "trailblazer-operation"
gem "view_component"

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "rspec-rails"

  gem "htmlbeautifier"
end

group :development do
  gem "web-console"
  gem "hotwire-livereload"
  gem "rubocop"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end

group :test do
  gem "capybara"
  gem "simplecov", require: false
end

# For Windows
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
