// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditGenderFormController from "./edit_gender_form_controller"
application.register("edit-gender-form", EditGenderFormController)

import Modal from "./modal_controller"
application.register("modal", Modal)
