name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: src/nubes
          bundler-cache: true

      - name: Create DB
        working-directory: src/nubes
        run: |
          bin/rails db:prepare

      - name: Run tests
        working-directory: src/nubes
        run: |
          bundle exec rspec